### ISSUE TITLE
Ajout d'une licence pour les données

### ISSUE THREAD

**Issue by bzg** [cget-carto/mission_coworking#4]
Bonjour,

les données de la base devraient être publiées sous une [licence de réutilisation](https://www.data.gouv.fr/fr/licences): soit l'ODbL, soit la licence Ouverte 2.0.

@cquest tu penses que laquelle serait plus adaptée?

**Comment by bzg** [comment]
Ah, @cquest vient de répondre dans https://github.com/cget-carto/mission_coworking/pull/3

Je laisse l'issue ouverte tant que la PR n'est pas mergée.

**Comment by cquest** [comment]
J'ai fait une PR avec la LO, mais il faut voir si il y a des sources ODbL vu que c'est une agrégation...

**Comment by bzg** [comment]
A première vue je dirais qu'il n'y a pas de sources ODbL mais je laisse @cget-carto ou @meloditerranee confirmer.

**Comment by bzg** [comment]
Merci !
