### ISSUE TITLE
Ajout GeoJSON

### ISSUE THREAD

**Issue by ThomasG77** [cget-carto/mission_coworking#9]
Pour pouvoir ajouter les espaces de coworking sur une carte, ce format est nettement plus pratique
Pour un aperçu en ligne en utilisant le visualisateur de Github https://github.com/ThomasG77/mission_coworking/blob/geojson/CGET_TiersLieux_2019.geojson
GeoJSON obtenu avec le logiciel CSVKit en utilisant la commande suivante:

    csvjson -e 'utf-8' -d ';' --lat LAT --lon LONG CGET_TiersLieux_2019.csv > CGET_TiersLieux_2019.geojson

Ceci en utilisant les données reformatées et/ou manquantes via ma PR #7

**Comment by bzg** [comment]
L'autre avantage d'un fichier `.geojson` est qu'il pourra être affiché directement via github.

**Comment by ThomasG77** [comment]
Fait par @bzg
